---
version: "3"
services:

  # NOTE TODO There's an issue w/ consul servers getting confused when their
  # ips change after a shutdown and restart. So we want to make sure consul
  # is always started w/ the same ip. We can get this to happen by control
  # over the dependency chain for now, but should be fixed later.
  consul:
    image: consul
    command: consul agent -config-dir /consul/config -encrypt ${CONSUL_ENCRYPT}
    container_name: consul
    restart: on-failure
    ports:
      - "127.0.0.1:8400:8400"
      - "127.0.0.1:8500:8500"
      - "127.0.0.1:8300-8302:8300-8302"
      - "127.0.0.1:8301-8302:8301-8302/udp"
      - "127.0.0.1:8600:8600"
      - "127.0.0.1:53:8600/udp"
    volumes:
      - ${HOME}/.config/consul:/consul/config
      - ${HOME}/.var/consul:/consul/data

  vault:
    image: vault
    command: vault server -config /vault/config
    container_name: vault
    restart: on-failure
    ports:
      - "127.0.0.1:8200:8200"
    volumes:
      - ${HOME}/.config/vault:/vault/config
      - ${HOME}/.var/vault:/vault/data
    cap_add:
      - IPC_LOCK
    # NOTE See note about consul ip issue above.
    depends_on:
      - consul
