#!/usr/bin/bash

export AWS_DEFAULT_REGION="us-west-1"

export AWS_ACCESS_KEY_ID="$(get-env-var GUDCODES_AWS_ACCESS_KEY_ID)"
export AWS_SECRET_ACCESS_KEY="$(get-env-var GUDCODES_AWS_SECRET_ACCESS_KEY)"
